export interface Skill {
  id: string;
  name: string;
  description: string;
  category: string;
  author?: string;
  url: string;
}

export const SKILLS: Skill[] = [
  // ── Document Processing ──
  {
    id: 'docx',
    name: 'Word Documents',
    description: 'Create, edit, and analyze Word docs with tracked changes, comments, and formatting.',
    category: 'Documents',
    url: 'https://github.com/anthropics/skills/tree/main/skills/docx',
  },
  {
    id: 'pdf',
    name: 'PDF Processing',
    description: 'Extract text, tables, and metadata from PDFs. Merge, split, and annotate documents.',
    category: 'Documents',
    url: 'https://github.com/anthropics/skills/tree/main/skills/pdf',
  },
  {
    id: 'pptx',
    name: 'Presentations',
    description: 'Read, generate, and adjust slides with layouts, templates, and speaker notes.',
    category: 'Documents',
    url: 'https://github.com/anthropics/skills/tree/main/skills/pptx',
  },
  {
    id: 'xlsx',
    name: 'Spreadsheets',
    description: 'Manipulate spreadsheets with formulas, charts, pivot tables, and data transformations.',
    category: 'Documents',
    url: 'https://github.com/anthropics/skills/tree/main/skills/xlsx',
  },
  {
    id: 'markdown-epub',
    name: 'Markdown to EPUB',
    description: 'Convert markdown documents and chat summaries into professional EPUB ebook files.',
    category: 'Documents',
    author: 'smerchek',
    url: 'https://github.com/smerchek/claude-epub-skill',
  },

  // ── Development ──
  {
    id: 'artifacts-builder',
    name: 'Artifacts Builder',
    description: 'Create elaborate, multi-component HTML artifacts using React, Tailwind CSS, and shadcn/ui.',
    category: 'Development',
    url: 'https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder',
  },
  {
    id: 'aws-skills',
    name: 'AWS Development',
    description: 'AWS development with CDK best practices, cost optimization, and serverless architecture patterns.',
    category: 'Development',
    author: 'zxkane',
    url: 'https://github.com/zxkane/aws-skills',
  },
  {
    id: 'changelog-generator',
    name: 'Changelog Generator',
    description: 'Automatically create user-facing changelogs by analyzing git history and transforming commits into release notes.',
    category: 'Development',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/changelog-generator',
  },
  {
    id: 'd3-visualization',
    name: 'D3.js Visualization',
    description: 'Produce D3 charts and interactive data visualizations directly from Claude Code.',
    category: 'Development',
    author: 'chrisvoncsefalvay',
    url: 'https://github.com/chrisvoncsefalvay/claude-d3js-skill',
  },
  {
    id: 'mcp-builder',
    name: 'MCP Builder',
    description: 'Build high-quality MCP servers for integrating external APIs and services with LLMs using Python or TypeScript.',
    category: 'Development',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/mcp-builder',
  },
  {
    id: 'ios-simulator',
    name: 'iOS Simulator',
    description: 'Interact with iOS Simulator for testing and debugging iOS applications directly from Claude.',
    category: 'Development',
    author: 'conorluddy',
    url: 'https://github.com/conorluddy/ios-simulator-skill',
  },
  {
    id: 'playwright',
    name: 'Playwright Automation',
    description: 'Model-invoked Playwright automation for testing and validating web applications.',
    category: 'Development',
    author: 'lackeyjb',
    url: 'https://github.com/lackeyjb/playwright-skill',
  },
  {
    id: 'webapp-testing',
    name: 'Webapp Testing',
    description: 'Test local web applications using Playwright for verifying frontend functionality and capturing screenshots.',
    category: 'Development',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/webapp-testing',
  },
  {
    id: 'tdd',
    name: 'Test-Driven Development',
    description: 'Implement features and bugfixes using TDD methodology — write tests before implementation code.',
    category: 'Development',
    url: 'https://github.com/obra/superpowers/tree/main/skills/test-driven-development',
  },
  {
    id: 'subagent-development',
    name: 'Subagent-Driven Dev',
    description: 'Dispatch independent subagents for individual tasks with code review checkpoints between iterations.',
    category: 'Development',
    url: 'https://github.com/NeoLabHQ/context-engineering-kit/tree/master/plugins/sadd/skills/subagent-driven-development',
  },
  {
    id: 'git-worktrees',
    name: 'Git Worktrees',
    description: 'Create isolated git worktrees with smart directory selection and safety verification.',
    category: 'Development',
    url: 'https://github.com/obra/superpowers/blob/main/skills/using-git-worktrees/',
  },
  {
    id: 'software-architecture',
    name: 'Software Architecture',
    description: 'Apply Clean Architecture, SOLID principles, and comprehensive design patterns to your codebase.',
    category: 'Development',
    url: 'https://github.com/NeoLabHQ/context-engineering-kit/tree/master/plugins/ddd/skills/software-architecture',
  },
  {
    id: 'finishing-branch',
    name: 'Finishing a Branch',
    description: 'Guide completion of development work by presenting clear options and handling the chosen workflow.',
    category: 'Development',
    url: 'https://github.com/obra/superpowers/tree/main/skills/finishing-a-development-branch',
  },
  {
    id: 'prompt-engineering',
    name: 'Prompt Engineering',
    description: 'Apply well-known prompt engineering techniques including Anthropic best practices and agent persuasion patterns.',
    category: 'Development',
    url: 'https://github.com/NeoLabHQ/context-engineering-kit/tree/master/plugins/customaize-agent/skills/prompt-engineering',
  },
  {
    id: 'skill-creator',
    name: 'Skill Creator',
    description: 'Build effective Claude Skills that extend capabilities with specialized knowledge, workflows, and tool integrations.',
    category: 'Development',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/skill-creator',
  },
  {
    id: 'skill-seekers',
    name: 'Skill Seekers',
    description: 'Automatically convert any documentation website into a Claude AI skill in minutes.',
    category: 'Development',
    author: 'yusufkaraaslan',
    url: 'https://github.com/yusufkaraaslan/Skill_Seekers',
  },
  {
    id: 'move-code-quality',
    name: 'Move Code Quality',
    description: 'Analyze Move language packages against the official Move Book Code Quality Checklist for best practices.',
    category: 'Development',
    author: '1NickPappas',
    url: 'https://github.com/1NickPappas/move-code-quality-skill',
  },
  {
    id: 'pypict',
    name: 'PICT Test Design',
    description: 'Design comprehensive test cases using pairwise independent combinatorial testing for optimized test suites.',
    category: 'Development',
    author: 'omkamal',
    url: 'https://github.com/omkamal/pypict-claude-skill',
  },

  // ── Data & Research ──
  {
    id: 'csv-summarizer',
    name: 'CSV Data Summarizer',
    description: 'Automatically analyze CSV files and generate comprehensive insights with visualizations.',
    category: 'Data & Research',
    author: 'coffeefuelbump',
    url: 'https://github.com/coffeefuelbump/csv-data-summarizer-claude-skill',
  },
  {
    id: 'deep-research',
    name: 'Deep Research',
    description: 'Execute autonomous multi-step research using Gemini for market analysis, competitive landscaping, and literature reviews.',
    category: 'Data & Research',
    author: 'sanjay3290',
    url: 'https://github.com/sanjay3290/ai-skills/tree/main/skills/deep-research',
  },
  {
    id: 'postgres',
    name: 'PostgreSQL Queries',
    description: 'Execute safe read-only SQL queries against PostgreSQL databases with multi-connection support and defense-in-depth security.',
    category: 'Data & Research',
    author: 'sanjay3290',
    url: 'https://github.com/sanjay3290/ai-skills/tree/main/skills/postgres',
  },
  {
    id: 'langsmith-fetch',
    name: 'LangSmith Fetch',
    description: 'Debug LangChain and LangGraph agents by fetching and analyzing execution traces from LangSmith Studio.',
    category: 'Data & Research',
    author: 'OthmanAdi',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/langsmith-fetch',
  },
  {
    id: 'root-cause-tracing',
    name: 'Root Cause Tracing',
    description: 'Trace errors deep in execution back to their original trigger using systematic debugging methodology.',
    category: 'Data & Research',
    url: 'https://github.com/obra/superpowers/tree/main/skills/root-cause-tracing',
  },

  // ── Writing & Content ──
  {
    id: 'brainstorming',
    name: 'Brainstorming',
    description: 'Transform rough ideas into fully-formed designs through structured questioning and alternative exploration.',
    category: 'Writing & Content',
    url: 'https://github.com/obra/superpowers/tree/main/skills/brainstorming',
  },
  {
    id: 'content-research-writer',
    name: 'Content Research Writer',
    description: 'Write high-quality content with research, citations, improved hooks, and section-by-section feedback.',
    category: 'Writing & Content',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/content-research-writer',
  },
  {
    id: 'article-extractor',
    name: 'Article Extractor',
    description: 'Extract full article text and metadata from any web page for analysis and summarization.',
    category: 'Writing & Content',
    url: 'https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/article-extractor',
  },
  {
    id: 'meeting-insights',
    name: 'Meeting Insights',
    description: 'Analyze meeting transcripts to uncover patterns like conflict avoidance, speaking ratios, and leadership style.',
    category: 'Writing & Content',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/meeting-insights-analyzer',
  },
  {
    id: 'twitter-optimizer',
    name: 'Twitter Algorithm Optimizer',
    description: 'Analyze and optimize tweets for maximum reach using Twitter\'s open-source algorithm insights.',
    category: 'Writing & Content',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/twitter-algorithm-optimizer',
  },
  {
    id: 'internal-comms',
    name: 'Internal Comms',
    description: 'Write internal communications including updates, newsletters, FAQs, status reports, and project updates.',
    category: 'Writing & Content',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/internal-comms',
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM Integration',
    description: 'Chat directly with NotebookLM for source-grounded answers based exclusively on your uploaded documents.',
    category: 'Writing & Content',
    author: 'PleasePrompto',
    url: 'https://github.com/PleasePrompto/notebooklm-skill',
  },

  // ── Creative & Media ──
  {
    id: 'canvas-design',
    name: 'Canvas Design',
    description: 'Create beautiful visual art in PNG and PDF using design philosophy and aesthetic principles.',
    category: 'Creative & Media',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/canvas-design',
  },
  {
    id: 'imagen',
    name: 'Image Generation',
    description: 'Generate images using Google Gemini\'s API for UI mockups, icons, illustrations, and visual assets.',
    category: 'Creative & Media',
    author: 'sanjay3290',
    url: 'https://github.com/sanjay3290/ai-skills/tree/main/skills/imagen',
  },
  {
    id: 'image-enhancer',
    name: 'Image Enhancer',
    description: 'Improve image and screenshot quality by enhancing resolution, sharpness, and clarity.',
    category: 'Creative & Media',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/image-enhancer',
  },
  {
    id: 'theme-factory',
    name: 'Theme Factory',
    description: 'Apply professional font and color themes to artifacts including slides, docs, reports, and landing pages.',
    category: 'Creative & Media',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/theme-factory',
  },
  {
    id: 'youtube-transcript',
    name: 'YouTube Transcript',
    description: 'Fetch transcripts from YouTube videos and prepare summaries for research and note-taking.',
    category: 'Creative & Media',
    url: 'https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/youtube-transcript',
  },
  {
    id: 'slack-gif',
    name: 'Slack GIF Creator',
    description: 'Create animated GIFs optimized for Slack with size validators and composable animation primitives.',
    category: 'Creative & Media',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/slack-gif-creator',
  },
  {
    id: 'video-downloader',
    name: 'Video Downloader',
    description: 'Download videos from YouTube and other platforms with support for various formats and quality options.',
    category: 'Creative & Media',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/video-downloader',
  },

  // ── Productivity ──
  {
    id: 'file-organizer',
    name: 'File Organizer',
    description: 'Intelligently organize files and folders by understanding context, finding duplicates, and suggesting better structures.',
    category: 'Productivity',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/file-organizer',
  },
  {
    id: 'invoice-organizer',
    name: 'Invoice Organizer',
    description: 'Automatically organize invoices and receipts for tax preparation by reading, extracting, and renaming files.',
    category: 'Productivity',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/invoice-organizer',
  },
  {
    id: 'tailored-resume',
    name: 'Tailored Resume Generator',
    description: 'Analyze job descriptions and generate tailored resumes that highlight relevant experience and skills.',
    category: 'Productivity',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/tailored-resume-generator',
  },
  {
    id: 'kaizen',
    name: 'Kaizen',
    description: 'Apply continuous improvement methodology with analytical approaches based on Japanese Kaizen and Lean principles.',
    category: 'Productivity',
    url: 'https://github.com/NeoLabHQ/context-engineering-kit/tree/master/plugins/kaizen/skills/kaizen',
  },
  {
    id: 'n8n-skills',
    name: 'n8n Workflows',
    description: 'Understand and operate n8n automation workflows directly from Claude Code.',
    category: 'Productivity',
    author: 'haunchen',
    url: 'https://github.com/haunchen/n8n-skills',
  },
  {
    id: 'domain-brainstormer',
    name: 'Domain Name Brainstormer',
    description: 'Generate creative domain name ideas and check availability across .com, .io, .dev, and .ai extensions.',
    category: 'Productivity',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/domain-name-brainstormer',
  },
  {
    id: 'lead-research',
    name: 'Lead Research Assistant',
    description: 'Identify and qualify high-quality leads by analyzing your product and providing actionable outreach strategies.',
    category: 'Productivity',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/lead-research-assistant',
  },
  {
    id: 'competitive-ads',
    name: 'Competitive Ads Extractor',
    description: 'Extract and analyze competitors\' ads from ad libraries to understand messaging and creative approaches.',
    category: 'Productivity',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/competitive-ads-extractor',
  },
  {
    id: 'family-history',
    name: 'Family History Research',
    description: 'Plan and organize family history and genealogy research projects with structured methodology.',
    category: 'Productivity',
    author: 'emaynard',
    url: 'https://github.com/emaynard/claude-family-history-research-skill',
  },

  // ── Security ──
  {
    id: 'ffuf',
    name: 'FFUF Web Fuzzing',
    description: 'Run ffuf web fuzzer tasks and analyze results for vulnerabilities in web applications.',
    category: 'Security',
    author: 'jthack',
    url: 'https://github.com/jthack/ffuf_claude_skill',
  },
  {
    id: 'threat-hunting',
    name: 'Threat Hunting with Sigma',
    description: 'Use Sigma detection rules to hunt for threats and analyze security events across log sources.',
    category: 'Security',
    author: 'jthack',
    url: 'https://github.com/jthack/threat-hunting-with-sigma-rules-skill',
  },
  {
    id: 'computer-forensics',
    name: 'Computer Forensics',
    description: 'Digital forensics analysis and investigation techniques for incident response and evidence collection.',
    category: 'Security',
    url: 'https://github.com/mhattingpete/claude-skills-marketplace/tree/main/computer-forensics-skills/skills/computer-forensics',
  },
  {
    id: 'metadata-extraction',
    name: 'Metadata Extraction',
    description: 'Extract and analyze file metadata for forensic purposes and security investigations.',
    category: 'Security',
    url: 'https://github.com/mhattingpete/claude-skills-marketplace/tree/main/computer-forensics-skills/skills/metadata-extraction',
  },

  // ── Automation ──
  {
    id: 'connect',
    name: 'Connect (1000+ Apps)',
    description: 'Connect Claude to any app. Send emails, create issues, post messages, and take actions across 1000+ services.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/connect',
  },
  {
    id: 'github-automation',
    name: 'GitHub',
    description: 'Automate GitHub: issues, PRs, repos, branches, actions, and code search.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/github-automation',
  },
  {
    id: 'slack-automation',
    name: 'Slack',
    description: 'Automate Slack: messages, channels, search, reactions, threads, and scheduling.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/slack-automation',
  },
  {
    id: 'gmail-automation',
    name: 'Gmail',
    description: 'Automate Gmail: send and reply to emails, search, manage labels, drafts, and attachments.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/gmail-automation',
  },
  {
    id: 'notion-automation',
    name: 'Notion',
    description: 'Automate Notion: pages, databases, blocks, comments, and search across your workspace.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/notion-automation',
  },
  {
    id: 'jira-automation',
    name: 'Jira',
    description: 'Automate Jira: issues, projects, boards, sprints, and JQL queries.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/jira-automation',
  },
  {
    id: 'linear-automation',
    name: 'Linear',
    description: 'Automate Linear: issues, projects, cycles, teams, and workflows.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/linear-automation',
  },
  {
    id: 'figma-automation',
    name: 'Figma',
    description: 'Automate Figma: files, components, comments, projects, and team management.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/figma-automation',
  },
  {
    id: 'google-drive-automation',
    name: 'Google Drive',
    description: 'Automate Google Drive: upload, download, search, share, and organize files.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/google-drive-automation',
  },
  {
    id: 'google-calendar-automation',
    name: 'Google Calendar',
    description: 'Automate Google Calendar: events, attendees, free/busy checks, and recurring schedules.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/google-calendar-automation',
  },
  {
    id: 'stripe-automation',
    name: 'Stripe',
    description: 'Automate Stripe: charges, customers, products, subscriptions, and refunds.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/stripe-automation',
  },
  {
    id: 'vercel-automation',
    name: 'Vercel',
    description: 'Automate Vercel: deployments, projects, domains, environment variables, and logs.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/vercel-automation',
  },
  {
    id: 'shopify-automation',
    name: 'Shopify',
    description: 'Automate Shopify: products, orders, customers, inventory, and GraphQL queries.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/shopify-automation',
  },
  {
    id: 'discord-automation',
    name: 'Discord',
    description: 'Automate Discord: messages, channels, servers, roles, and reactions.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/discord-automation',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    description: 'Suite of Google Workspace integrations: Gmail, Calendar, Chat, Docs, Sheets, Slides, and Drive.',
    category: 'Automation',
    author: 'sanjay3290',
    url: 'https://github.com/sanjay3290/ai-skills/tree/main/skills',
  },
  {
    id: 'sentry-automation',
    name: 'Sentry',
    description: 'Automate Sentry: issues, events, projects, releases, and alerts.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/sentry-automation',
  },
  {
    id: 'hubspot-automation',
    name: 'HubSpot',
    description: 'Automate HubSpot CRM: contacts, deals, companies, tickets, and email engagement.',
    category: 'Automation',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills/tree/main/hubspot-automation',
  },
];

export const SKILL_CATEGORIES = [
  'All',
  'Development',
  'Automation',
  'Documents',
  'Data & Research',
  'Writing & Content',
  'Creative & Media',
  'Productivity',
  'Security',
] as const;
